Django/giw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('preguntas/', include('preguntas.urls')),
    path('admin/', admin.site.urls)
]

Django/preguntas/urls.py
from django.urls import path

from . import views

# Imprescindible dar un nombre para crear un namespace y poder referirse a estas rutas como
# opiniones:index, opiniones:login, etc.
app_name = "preguntas"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginfunct, name='login'),
    path('logout', views.logoutfunct, name='logout'),
    path('<int:id>', views.preguntasN, name='pregunta'),
    path('<int:id>/respuesta', views.respuestaN, name='respuesta')
]

Django/preguntas/models.py
from django.db import models
from django.conf import settings
from django.utils.html import escape

# Create your models here.
class Pregunta(models.Model):
    #Clave primaria
    id = models.BigAutoField(primary_key=True, null=False)

    #Titulo de maximo 250 caracteres
    titulo = models.CharField(max_length=250, null=False)

    #Texto de maximo 5000 caracteres
    texto = models.CharField(max_length=5000, null=False)

    #Al crear una pregunta se asigna la fecha actual
    fecha = models.DateTimeField(auto_now_add=True, null=False)

    #Referencia a un usuario del sistema. Si se elimina el usuario, todas las preguntas asociadas a dicho usuario se borran
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE)

    def clean(self):
        '''Escapa datos'''
        self.titulo = escape(self.titulo)
        self.texto = escape(self.texto)
    
    #Devuelve el numero de respuestas de la pregunta
    def num_respuestas(self):
        return len(Respuesta.objects.filter(pregunta__exact=self))

    def __str__(self):
        """Para mostrar detalles en la interfaz admin"""
        return f"Pregunta (Titulo: {self.titulo}, Texto: {self.texto}, Autor: {self.autor})"

class Respuesta(models.Model):
    #Clave primaria
    id = models.BigAutoField(primary_key=True, null=False)

    #Texto de maximo 5000 caracteres
    texto = models.CharField(max_length=5000, null=False)

    #Al crear una pregunta se asigna la fecha actual
    fecha = models.DateTimeField(auto_now_add=True, null=False)

    #Referencia a un usuario del sistema. Si se elimina el usuario, todas las respuestas de ese usuario se borran
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE)

    #Referencia a una pregunta. Si se elimina la pregunta, todas las respuestas de esa pregunta se borran
    pregunta = models.ForeignKey(Pregunta, null=False, on_delete=models.CASCADE)

    def clean(self):
        '''Escapa datos'''
        self.texto = escape(self.texto)

    def __str__(self):
        """Para mostrar detalles en la interfaz admin"""
        return f"Respuesta ({self.pregunta}, Respuesta de la pregunta: {self.texto}, Autor: {self.autor})"

Django/preguntas/forms.py
from django import forms

class LoginForm(forms.Form):
    """Formulario para autenticar usuarios"""
    username = forms.CharField(label='Nombre de usuario', max_length=100)
    password = forms.CharField(label='Contraseña', max_length=100, widget=forms.PasswordInput)

class NewQuestionForm(forms.Form):
    """Formulario para añadir una pregunta"""
    titulo = forms.CharField(label='Título', max_length=250)
    texto = forms.CharField(label='Texto', widget=forms.Textarea, max_length=5000)

class NewAnswerForm(forms.Form):
    """Formulario para añadir una respuesta a una pregunta"""
    texto = forms.CharField(label='Respuesta', widget=forms.Textarea, max_length=5000)

Django/preguntas/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.core.exceptions import ValidationError

from .models import Pregunta, Respuesta
from .forms import LoginForm, NewQuestionForm, NewAnswerForm
# Create your views here.

@login_required(login_url='preguntas:login')
def indexPost(request):
    # Carga el formulario desde los datos de la petición y lo valida
    form = NewQuestionForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")
    
    #Toma los datos limpios del formulario
    titulo = form.cleaned_data['titulo']
    texto = form.cleaned_data['texto']

    #Crea un objeto ORM a partir de los datos limpios del formulario y lo salva en la BD
    p = Pregunta(titulo=titulo, texto=texto, autor=request.user)
    try:
        p.full_clean()
        p.save()
    except ValidationError as e:
        return HttpResponseBadRequest("Pregunta mal formada")
    return redirect(reverse('preguntas:index'))

@require_http_methods(["GET", "POST"])
def index(request):
    if request.method == "GET":
        #Muestra todas las preguntas de mas recientes a mas antiguas
        form = NewQuestionForm()
        preguntas = Pregunta.objects.order_by('-fecha')
        return render(request, "preguntas.html", {'preguntas':preguntas, 'NewQuestionForm':form})

    if request.method == "POST":
        #Añade una pregunta
        return indexPost(request)
        
@require_http_methods(["GET", "POST"])
def loginfunct(request):
    """Muestra el formulario (GET) o recibe los datos y realiza la autenticacion (POST)"""
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {'login_form': form})

    form = LoginForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    #Toma los datos limpios del formulario
    username = form.cleaned_data['username']
    password = form.cleaned_data['password']

    #Realiza la autenticación
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)  # Registra el usuario en la sesión
        return redirect(reverse('preguntas:index'))
    else:
        return render(request, "loginError.html")

@login_required(login_url='preguntas:login')
@require_GET
def logoutfunct(request):
    """Elimina al usuario de la sesión actual"""
    logout(request)  # Elimina el usuario de la sesión
    return redirect(reverse('preguntas:index'))

@login_required(login_url='preguntas:login')
@require_GET
def preguntasN(request, id):
    """Muestra la pregunta N y sus respuestas"""
    form = NewAnswerForm()

    #Obtener la pregunta N, en caso de que no exista genera un error 404
    pregunta = get_object_or_404(Pregunta, pk=id)

    #Ordenar la respuestas de lo mas reciente a lo mas antiguo
    respuestas = Respuesta.objects.filter(pregunta__exact=pregunta).order_by('-fecha')
    return render(request, "pregunta.html", {'pregunta':pregunta, 'respuestas':respuestas, 'NewAnswerForm':form})

@login_required(login_url='preguntas:login')
@require_POST
def respuestaN(request, id):
    """Recibe datos del formulario y realiza la publicacion de una respuesta asociada a la pregunta N (POST)"""
    #Obtener la pregunta N, en caso de que no exista genera un error 404
    pregunta = get_object_or_404(Pregunta, pk=id)

    # Carga el formulario desde los datos de la petición y lo valida
    form = NewAnswerForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    #Toma los datos limpios del formulario
    texto = form.cleaned_data['texto']

    #Crea un objeto ORM a partir de los datos limpios del formulario y lo salva en la BD
    r = Respuesta(texto=texto, autor=request.user, pregunta=pregunta)
    try:
        r.full_clean()
        r.save()
    except ValidationError as e:
        return HttpResponseBadRequest("Respuesta mal formada")
    return redirect(reverse('preguntas:pregunta', args=(id,)))

Django/preguntas/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TITULO{% endblock %}
    </title>
</head>
<body>
<h1>La web para preguntas y respuestas</h1>
<p>
{% if request.user.username %}
Bienvenido {{request.user.username}}
<a href="{% url 'preguntas:logout' %}"><button type="button">Cerrar sesión</button></a>
<a href="{% url 'preguntas:index' %}"><button type="button">Ver preguntas</button></a>
{% else %}
No autenticado <a href="{% url 'preguntas:login' %}"><button type="button">Iniciar sesión</button></a>
{% endif %}
</p>
{% block content %}
CONTENIDO
{% endblock %}
</body>
</html>

Django/preguntas/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}
{% block content %}
<form action="{% url 'preguntas:login' %}" method="post">
    <table>
    {{ login_form }}
    </table>
    {% csrf_token %}
    <button type="submit">Iniciar sesión</button>
</form>
{% endblock %}

Django/preguntas/templates/loginError.html
{% extends "base.html" %}

{% block title %}
Error de login
{% endblock %}
{% block content %}
<h2>Usuario o contraseña no válidos</h2>
{% endblock %}

Django/preguntas/templates/pregunta.html
{% extends "base.html" %}

{% block title %}
Respuestas de {{pregunta.titulo}}
{% endblock %}
{% block content %}
<h2>{{pregunta.titulo}} -- {{pregunta.autor.username}} ({{pregunta.fecha|date:"d \d\e F \d\e Y \a \l\a\s H:i"}})</h2>
<p>{{pregunta.texto}}</p>

<h2>Respuestas</h2>
<ol>
{% for respuesta in respuestas %}
    <li>{{respuesta.texto}}<br/>
        {{respuesta.autor.username}} ({{respuesta.fecha|date:"d \d\e F \d\e Y \a \l\a\s H:i"}})
    </li>
{% endfor %}
</ol>

<h2>Añadir nueva respuesta</h2>
<form action="{% url 'preguntas:respuesta' pregunta.id %}" method="post">
    <table>
    {{ NewAnswerForm }}
    </table>
    {% csrf_token %}
    <button type="submit">Enviar respuesta</button>
</form>
{% endblock %}

Django/preguntas/templates/preguntas.html
{% extends "base.html" %}

{% block title %}
Preguntas
{% endblock %}
{% block content %}
<h2>Preguntas</h2>
<ul>
{% for pregunta in preguntas %}
    <li><a href="{% url 'preguntas:pregunta' pregunta.id %}">{{pregunta.titulo}}</a> -- {{pregunta.autor.username}} ({{pregunta.fecha|date:"d \d\e F \d\e Y \a \l\a\s H:i"}})<br/>
        {{pregunta.num_respuestas}} Respuestas
    </li>
{% endfor %}
</ul>

{% if request.user.username %}
<h2>Añadir nueva pregunta</h2>
<form action="{% url 'preguntas:index' %}" method="post">
    <table>
    {{ NewQuestionForm }}
    </table>
    {% csrf_token %}
    <button type="submit">Enviar pregunta</button>
</form>
{% endif %}
{% endblock %}